package com.tiempoplaya.model;
// Generated Dec 19, 2018 12:27:53 AM by Hibernate Tools 4.3.1

import java.sql.Timestamp;
import javax.xml.bind.annotation.*;

/**
 * TDatos generated by hbm2java
 */
@XmlRootElement(name = "dato")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlSeeAlso({TPlayas.class})
public class TDatos implements java.io.Serializable {

    @XmlElement(name = "id")
    private int id;

    @XmlElement(name = "fotografia_id")
    private TFotografias TFotografias;

    @XmlElement(name = "playa_id")
    private TPlayas TPlayas;

    @XmlElement(name = "usuario_id")
    private TUsuarios TUsuarios;

    @XmlElement(name = "coordUTMx")
    private String coordUTMx;

    @XmlElement(name = "coordUTMy")
    private String coordUTMy;

    @XmlElement(name = "coordUTMz")
    private String coordUTMz;

    @XmlElement(name = "viento")
    private int viento;

    @XmlElement(name = "oleaje")
    private int oleaje;

    @XmlElement(name = "nubosidad")
    private int nubosidad;

    @XmlElement(name = "ocupacion")
    private int ocupacion;

    @XmlElement(name = "limpieza_agua")
    private int limpiezaAgua;

    @XmlElement(name = "limpieza_arena")
    private int limpiezaArena;
    
    @XmlElement(name = "medusas")
    private int medusas;

    @XmlElement(name = "bandera_mar")
    private int banderaMar;
    
    @XmlElement(name="timestamp")
    private Timestamp timestamp;

    public TDatos() {
    }
    
    public TDatos(TPlayas TPlayas, String coordUTMx, String coordUTMy, String coordUTMz, Timestamp timestamp) {
        
        this.TPlayas = TPlayas;
        
        this.coordUTMx = coordUTMx;
        this.coordUTMy = coordUTMy;
        this.coordUTMz = coordUTMz;
        
        this.timestamp = timestamp;
    }
    
    public TDatos(TUsuarios TUsuarios, TPlayas TPlayas, TFotografias TFotografias, String coordUTMx, String coordUTMy, String coordUTMz, int viento, int oleaje, int nubosidad, int ocupacion, int limpiezaAgua, int limpiezaArena, int banderaMar, int medusas, Timestamp timestamp) {
        this.TFotografias = TFotografias;
        this.TPlayas = TPlayas;
        this.TUsuarios = TUsuarios;
         
        this.coordUTMx = coordUTMx;
        this.coordUTMy = coordUTMy;
        this.coordUTMz = coordUTMz;
        this.viento = viento;
        this.oleaje = oleaje;
        this.nubosidad = nubosidad;
        this.ocupacion = ocupacion;
        this.limpiezaAgua = limpiezaAgua;
        this.limpiezaArena = limpiezaArena;
        this.banderaMar = banderaMar;
        this.medusas = medusas;
        this.timestamp = timestamp;
    }

    public Timestamp getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Timestamp timestamp) {
        this.timestamp = timestamp;
    }
    
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public TFotografias getTFotografias() {
        return this.TFotografias;
    }

    public void setTFotografias(TFotografias TFotografias) {
        this.TFotografias = TFotografias;
    }

    public TPlayas getTPlayas() {
        return this.TPlayas;
    }

    public void setTPlayas(TPlayas TPlayas) {
        this.TPlayas = TPlayas;
    }

    public TUsuarios getTUsuarios() {
        return this.TUsuarios;
    }

    public void setTUsuarios(TUsuarios TUsuarios) {
        this.TUsuarios = TUsuarios;
    }

    public String getCoordUTMx() {
        return coordUTMx;
    }

    public void setCoordUTMx(String coordUTMx) {
        this.coordUTMx = coordUTMx;
    }

    public String getCoordUTMy() {
        return coordUTMy;
    }

    public void setCoordUTMy(String coordUTMy) {
        this.coordUTMy = coordUTMy;
    }

    public String getCoordUTMz() {
        return coordUTMz;
    }

    public void setCoordUTMz(String coordUTMz) {
        this.coordUTMz = coordUTMz;
    }

    public int getViento() {
        return this.viento;
    }

    public void setViento(int viento) {
        this.viento = viento;
    }

    public int getOleaje() {
        return this.oleaje;
    }

    public void setOleaje(int oleaje) {
        this.oleaje = oleaje;
    }

    public int getNubosidad() {
        return this.nubosidad;
    }

    public void setNubosidad(int nubosidad) {
        this.nubosidad = nubosidad;
    }

    public int getOcupacion() {
        return this.ocupacion;
    }

    public void setOcupacion(int ocupacion) {
        this.ocupacion = ocupacion;
    }

    public int getLimpiezaAgua() {
        return this.limpiezaAgua;
    }

    public void setLimpiezaAgua(int limpiezaAgua) {
        this.limpiezaAgua = limpiezaAgua;
    }

    public int getLimpiezaArena() {
        return this.limpiezaArena;
    }

    public void setLimpiezaArena(int limpiezaArena) {
        this.limpiezaArena = limpiezaArena;
    }

    public int getBanderaMar() {
        return this.banderaMar;
    }

    public void setBanderaMar(int banderaMar) {
        this.banderaMar = banderaMar;
    }

    public int getMedusas() {
        return medusas;
    }

    public void setMedusas(int medusas) {
        this.medusas = medusas;
    }

    @Override
    public String toString() {
        return "TDatos{" + "id=" + id + ", TFotografias=" + TFotografias + ", TPlayas=" + TPlayas + ", TUsuarios=" + TUsuarios + ", coordUTMx=" + coordUTMx + ", coordUTMy=" + coordUTMy + ", coordUTMz=" + coordUTMz + ", viento=" + viento + ", oleaje=" + oleaje + ", nubosidad=" + nubosidad + ", ocupacion=" + ocupacion + ", limpiezaAgua=" + limpiezaAgua + ", limpiezaArena=" + limpiezaArena + ", medusas=" + medusas + ", banderaMar=" + banderaMar + '}';
    }

    
}
