package com.tiempoplaya.model;
// Generated Dec 19, 2018 12:27:53 AM by Hibernate Tools 4.3.1

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * TFotografias generated by hbm2java
 */
@XmlRootElement (name = "foto")
@XmlAccessorType(XmlAccessType.FIELD)
public class TFotografias implements java.io.Serializable {

    @XmlElement(name = "id")
    private int id;
    
    @XmlElement(name = "id_playa")
    private TPlayas TPlayas;
    
    @XmlElement(name = "id_usuario")
    private TUsuarios TUsuarios;
    
    @XmlElement(name = "b_fotografia")
    private byte[] BFotografia;
    
    @XmlElement(name = "timestamp")
    private Timestamp timestamp;
    
    @XmlElement(name = "filename")
    private String filename;
    
    @XmlElement(name = "enabled")
    private Integer enabled;
       
    @XmlElementWrapper(name="datos")
    @XmlElement(name="id")
    private Set<TDatos> TDatoses = new HashSet<TDatos>(0);

    public TFotografias() {
    }

    public TFotografias(TPlayas TPlayas, TUsuarios TUsuarios, byte[] BFotografia, Timestamp timestamp, String filename, Integer enabled) {
        this.TPlayas = TPlayas;
        this.TUsuarios = TUsuarios;
        this.BFotografia = BFotografia;
        this.timestamp = timestamp;
        this.filename = filename;
        this.enabled = enabled;
    }

    public Timestamp getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Timestamp timestamp) {
        this.timestamp = timestamp;
    }

    public TFotografias(TPlayas TPlayas) {
        this.TPlayas = TPlayas;
    }

    public TFotografias(TUsuarios TUsuarios) {
        this.TUsuarios = TUsuarios;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public TPlayas getTPlayas() {
        return this.TPlayas;
    }

    public void setTPlayas(TPlayas TPlayas) {
        this.TPlayas = TPlayas;
    }

    public TUsuarios getTUsuarios() {
        return this.TUsuarios;
    }

    public void setTUsuarios(TUsuarios TUsuarios) {
        this.TUsuarios = TUsuarios;
    }

    public byte[] getBFotografia() {
        return this.BFotografia;
    }

    public void setBFotografia(byte[] BFotografia) {
        this.BFotografia = BFotografia;
    }

    public Set<TDatos> getTDatoses() {
        return this.TDatoses;
    }

    public void setTDatoses(Set<TDatos> TDatoses) {
        this.TDatoses = TDatoses;
    }

    public Integer getEnabled() {
        return enabled;
    }

    public void setEnabled(Integer enabled) {
        this.enabled = enabled;
    }

    public String getFilename() {
        return filename;
    }

    public void setFilename(String filename) {
        this.filename = filename;
    }

    @Override
    public String toString() {
        return "TFotografias{" + "id=" + id + ", TPlayas=" + TPlayas + ", TUsuarios=" + TUsuarios + ", timestamp=" + timestamp + ", filename=" + filename + '}';
    }
    
}
