package com.tiempoplaya.model;
// Generated Dec 19, 2018 12:27:53 AM by Hibernate Tools 4.3.1

import java.text.NumberFormat;
import java.text.ParseException;
import java.util.HashSet;
import java.util.Locale;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.xml.bind.annotation.*;

/**
 * TPlayas generated by hbm2java
 */
@XmlRootElement(name = "playa")
@XmlAccessorType(XmlAccessType.FIELD)
public class TPlayas implements java.io.Serializable {

    private static final NumberFormat DF = NumberFormat.getInstance(new Locale("de", "DE"));

    @XmlElement(name = "id")
    private int id;

    @XmlElement(name = "nombre")
    private String nombre;

    @XmlElement(name = "coordUTMx")
    private String coordUTMx;

    @XmlElement(name = "coordUTMy")
    private String coordUTMy;

    @XmlElement(name = "coordUTMz")
    private String coordUTMz;
    
    @XmlElement(name = "utmzone")
    private Character utmzone;

    @XmlElement(name = "municipio")
    private String municipio;

    @XmlElement(name = "cp")
    private int cp;

    @XmlElement(name = "pais")
    private String pais;
    
    @XmlElement(name = "enabled")
    private int enabled;
    
    @XmlElement(name = "webcam")
    private String webcam;


    @XmlElementWrapper(name = "fotografias")
    @XmlElement(name = "id")
    private Set<TFotografias> TFotografiases = new HashSet<TFotografias>(0);

    @XmlElementWrapper(name = "datos")
    @XmlElement(name = "id")
    private Set<TDatos> TDatoses = new HashSet<TDatos>(0);

    public TPlayas() {
    }

    public TPlayas(String coordUTMx, String coordUTMy, String coordUTMz, Character utmzone, String nombre, String municipio, int cp, String pais) {
        this.nombre = nombre;
        this.coordUTMx = coordUTMx;
        this.coordUTMy = coordUTMy;
        this.coordUTMz = coordUTMz;
        this.utmzone = utmzone;
        this.municipio = municipio;
        this.cp = cp;
        this.pais = pais;
    }

    public TPlayas(int id, String nombre, String coordUTMx, String coordUTMy, String coordUTMz, Character utmzone, String municipio, int cp, String pais) {
        this.id = id;
        this.nombre = nombre;
        this.coordUTMx = coordUTMx;
        this.coordUTMy = coordUTMy;
        this.coordUTMz = coordUTMz;
        this.utmzone = utmzone;
        this.municipio = municipio;
        this.cp = cp;
        this.pais = pais;
    }
    
    public TPlayas(int id, String nombre, String coordUTMx, String coordUTMy, String coordUTMz, Character utmzone, String municipio, String pais) {
        this.id = id;
        this.nombre = nombre;
        this.coordUTMx = coordUTMx;
        this.coordUTMy = coordUTMy;
        this.coordUTMz = coordUTMz;
        this.utmzone = utmzone;
        this.municipio = municipio;
        this.pais = pais;
    }

    public TPlayas(int id, String nombre, String coordUTMx, String coordUTMy, String coordUTMz, Character utmzone, String municipio, int cp, String pais, Set<TFotografias> TFotografiases, Set<TDatos> TDatoses) {
        this.id = id;
        this.nombre = nombre;
        this.coordUTMx = coordUTMx;
        this.coordUTMy = coordUTMy;
        this.coordUTMz = coordUTMz;
        this.utmzone = utmzone;
        this.municipio = municipio;
        this.cp = cp;
        this.pais = pais;
        this.TFotografiases = TFotografiases;
        this.TDatoses = TDatoses;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Double getDoubleCoordUTMx() {

        Double d = 0.0;

        try {
            d = Double.valueOf(DF.parse(coordUTMx).doubleValue());
        } catch (ParseException ex) {
            Logger.getLogger(TPlayas.class.getName()).log(Level.SEVERE, null, ex);
        }

        return d;
    }

    public String getCoordUTMx() {
        return coordUTMx;
    }
    
    public void setCoordUTMx(String coordUTMx) {
        this.coordUTMx = coordUTMx;
    }

    public Double getDoubleCoordUTMy() {
        Double d = 0.0;

        try {
            d = Double.valueOf(DF.parse(coordUTMy).doubleValue());
        } catch (ParseException ex) {
            Logger.getLogger(TPlayas.class.getName()).log(Level.SEVERE, null, ex);
        }

        return d;
    }

    public String getCoordUTMy() {
        return coordUTMy;
    }
    
    public void setCoordUTMy(String coordUTMy) {
        this.coordUTMy = coordUTMy;
    }

    public Integer getIntCoordUTMz() {
        return Integer.parseInt(coordUTMz);
    }
    
    public String getCoordUTMz() {
        return coordUTMz;
    }

    public void setCoordUTMz(String coordUTMz) {
        this.coordUTMz = coordUTMz;
    }

    public String getMunicipio() {
        return this.municipio;
    }

    public void setMunicipio(String municipio) {
        this.municipio = municipio;
    }

    public int getCp() {
        return this.cp;
    }

    public void setCp(int cp) {
        this.cp = cp;
    }

    public int getEnabled() {
        return enabled;
    }

    public void setEnabled(int enabled) {
        this.enabled = enabled;
    }

    public String getPais() {
        return this.pais;
    }

    public void setPais(String pais) {
        this.pais = pais;
    }

    @Override
    public boolean equals(Object obj) {
        return super.equals(obj); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public int hashCode() {
        return super.hashCode(); //To change body of generated methods, choose Tools | Templates.
    }

    public Set<TFotografias> getTFotografiases() {
        return this.TFotografiases;
    }

    public void setTFotografiases(Set<TFotografias> TFotografiases) {
        this.TFotografiases = TFotografiases;
    }

    public Set<TDatos> getTDatoses() {
        return this.TDatoses;
    }

    public void setTDatoses(Set<TDatos> TDatoses) {
        this.TDatoses = TDatoses;
    }

    public Character getUtmzone() {
        return utmzone;
    }

    public void setUtmzone(Character utmzone) {
        this.utmzone = utmzone;
    }

    public String getWebcam() {
        return webcam;
    }

    public void setWebcam(String webcam) {
        this.webcam = webcam;
    }
    
    
    @Override
    public String toString() {
        return "TPlayas{" + "id=" + id + ", nombre=" + nombre + ", coordUTMx=" + coordUTMx + ", coordUTMy=" + coordUTMy + ", coordUTMz=" + coordUTMz+ utmzone + ", municipio=" + municipio + ", cp=" + cp + ", pais=" + pais + '}';
    }

}
