package com.tiempoplaya.model;
// Generated Dec 19, 2018 12:27:53 AM by Hibernate Tools 4.3.1


import java.io.UnsupportedEncodingException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;
import javax.xml.bind.annotation.*;

/**
 * TUsuarios generated by hbm2java
 */

@XmlRootElement (name="usuario")
@XmlAccessorType(XmlAccessType.FIELD)
public class TUsuarios  implements java.io.Serializable {

    @XmlElement(name="id")
    private int id;
    
    @XmlElement(name="nombre")
    private String nombre;
    
    @XmlElement(name="apellidos")
    private String apellidos;
    
    @XmlElement(name="usuario")
    private String usuario;
    
    @XmlElement(name="contrasenya")
    private String contrasenya;
    
    @XmlElement(name="email")
    private String email;
    
    @XmlElement(name="tk")
    private String tk;
    
    @XmlElement(name="id_grupo")
    private Integer id_grupo;
    
    @XmlElement(name="enabled")
    private Integer enabled;
    
    @XmlElement(name="tk_timestamp")
    private Timestamp tk_timestamp;
        
    @XmlElementWrapper(name="fotografias")
    @XmlElement(name="id")
    private Set<TFotografias> TFotografiases = new HashSet<TFotografias>(0);
    
    @XmlElementWrapper(name="datos")
    @XmlElement(name="id")
    private Set<TDatos> TDatoses = new HashSet<TDatos>(0);

    public TUsuarios() {
    }
    
    public TUsuarios(int id, String nombre, String apellidos, String email) {
        this.id = id;
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.email = email;  
    }
    
    public TUsuarios(String nombre, String apellidos, String usuario, String email) {
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.usuario = usuario;
        this.email = email;  
    }
    
    public TUsuarios(String nombre, String apellidos, String usuario, String email, String contrasenya, Integer grupo) {
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.usuario = usuario;
        this.email = email;  
        this.contrasenya = contrasenya;
        this.id_grupo = grupo;
    }
    
    public TUsuarios(int id, String nombre, String apellidos, String usuario, String email, String tk) {
        this.id = id;
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.usuario = usuario;
        this.email = email;  
        this.tk = tk;    
    }
    
    public TUsuarios(int id, String nombre, String apellidos, String usuario, String contrasenya, String email, String tk) {
        this.id = id;
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.usuario = usuario;
        this.contrasenya = contrasenya;
        this.email = email;  
        this.tk = tk;    
    }
    
    public TUsuarios(int id, String nombre, String apellidos, String usuario, Integer idgrupo, String email, String tk) {
        this.id = id;
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.usuario = usuario;
        this.id_grupo = idgrupo;
        this.email = email;  
        this.tk = tk;    
    }

    public TUsuarios(int id, String nombre, String apellidos, String usuario, String contrasenya, String email, String tk, Integer idgrupo, Timestamp tk_timestamp) {
        this.id = id;
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.usuario = usuario;
        this.contrasenya = contrasenya;
        this.email = email;
        this.tk = tk;
        this.id_grupo = idgrupo;
        this.tk_timestamp = tk_timestamp;
    }
       
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getApellidos() {
        return apellidos;
    }

    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getContrasenya() {
        return this.contrasenya;
    }
    
    public void setContrasenya(String contrasenya) {
        this.contrasenya = contrasenya;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public String getTk() {
        return tk;
    }

    public void setTk(String tk) {
        this.tk = tk;
    }

    public Integer getEnabled() {
        return enabled;
    }

    public void setEnabled(Integer enabled) {
        this.enabled = enabled;
    }
    
    public Timestamp getTk_timestamp() {
        return tk_timestamp;
    }

    public void setTk_timestamp(Timestamp tk_timestamp) {
        this.tk_timestamp = tk_timestamp;
    }

    public Integer getId_grupo() {
        return id_grupo;
    }

    public void setId_grupo(Integer id_grupo) {
        this.id_grupo = id_grupo;
    }
    
    public Set<TFotografias> getTFotografiases() {
        return this.TFotografiases;
    }
    
    public void setTFotografiases(Set<TFotografias> TFotografiases) {
        this.TFotografiases = TFotografiases;
    }
    public Set<TDatos> getTDatoses() {
        return this.TDatoses;
    }
    
    public void setTDatoses(Set<TDatos> TDatoses) {
        this.TDatoses = TDatoses;
    }

    @Override
    public boolean equals(Object obj) {
        return super.equals(obj); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public int hashCode() {
        return super.hashCode(); //To change body of generated methods, choose Tools | Templates.
    }
    
    public void setUserNull(){
        this.id = -1;
        this.nombre = "null_tiempoyplaya";
        this.apellidos = "null_tiempoyplaya";
        this.email = "null_tiempoyplaya@tiempoyplaya.tp";
        this.contrasenya = "null_password";
        this.usuario = "null_tiempoyplaya";
    }
    
    public static String createHash(String password) throws NoSuchAlgorithmException, UnsupportedEncodingException {
        MessageDigest digest = MessageDigest.getInstance("SHA-256");
        digest.update(password.getBytes("UTF-8"));
        byte byteData[] = digest.digest();
        //convert bytes to hex chars
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < byteData.length; i++) {
            sb.append(Integer.toString((byteData[i] & 0xff) + 0x100, 16).substring(1));
        }
        return sb.toString();
    }

    @Override
    public String toString() {
        return "TUsuarios{" + "id=" + id + ", nombre=" + nombre + ", apellidos=" + apellidos + ", usuario=" + usuario + ", email=" + email + ", tk_timestamp=" + tk_timestamp + '}';
    }

}


